-- 2022년 3월의 오프라인/온라인 상품 판매 데이터
-- OFFLINE 테이블의 USER_ID 값은 NULL

SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE,
    PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE_SALE
    WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
    UNION ALL
    SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE,
    PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT FROM OFFLINE_SALE
    WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
)
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;