SELECT A.SALES_DATE
     , A.PRODUCT_ID
     , A.USER_ID
     , A.SALES_AMOUNT
  FROM (
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE
     , PRODUCT_ID
     , USER_ID
     , SALES_AMOUNT
  FROM ONLINE_SALE
 WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202203'
 UNION ALL
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE
     , PRODUCT_ID
     , NULL AS USER_ID
     , SALES_AMOUNT
  FROM OFFLINE_SALE
 WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202203'
       )  A
 ORDER BY A.SALES_DATE
     , A.PRODUCT_ID
     , A.USER_ID