SELECT C.CAR_ID, C.CAR_TYPE, FLOOR(C.DAILY_FEE * (1 - (D.DISCOUNT_RATE/100)) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON D.CAR_TYPE = C.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단','SUV')
      AND D.DURATION_TYPE LIKE '30일%'
      AND FLOOR(C.DAILY_FEE * (1 - (D.DISCOUNT_RATE/100)) * 30) BETWEEN 500000 AND 2000000
      AND CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                         WHERE START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
                         AND END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD'))
ORDER BY 3 DESC, 2, 1 DESC;