SELECT
    USER_ID, NICKNAME, CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) 전체주소,
    CONCAT(LEFT(TLNO,3),'-',SUBSTRING(TLNO, 4, 4),'-',RIGHT(TLNO,4)) 전화번호
FROM USED_GOODS_BOARD b LEFT JOIN USED_GOODS_USER u
ON b.WRITER_ID = u.USER_ID
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3
ORDER BY USER_ID DESC