-- 보호소 전 안함 > 보호소 나갈 때는 중성화 됨

SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE 'Intact%' AND (O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR 
                                            O.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY 1;