WITH SUM AS(SELECT I.REST_ID, ROUND(AVG(REVIEW_SCORE),2) SCORE
FROM REST_INFO I
JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY REST_ID)
SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM REST_INFO I
JOIN SUM S ON I.REST_ID = S.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC