WITH MEMBER AS (
    SELECT USER_ID
    FROM   USER_INFO
    WHERE  JOINED >= DATE '2021-01-01'
           AND JOINED <= DATE '2021-12-31'
    )
 ,
SALE AS (
    SELECT     EXTRACT(YEAR FROM S.SALES_DATE) AS YEAR
             , EXTRACT(MONTH FROM S.SALES_DATE) AS MONTH
             , COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS
    FROM       ONLINE_SALE S
    INNER JOIN MEMBER M
               ON S.USER_ID = M.USER_ID
    GROUP BY   EXTRACT(YEAR FROM S.SALES_DATE)
             , EXTRACT(MONTH FROM S.SALES_DATE)
)
SELECT   YEAR
       , MONTH
       , PURCHASED_USERS
       , ROUND(PURCHASED_USERS / (SELECT COUNT(*) FROM MEMBER), 1) AS PUCHASED_RATIO
FROM     SALE
ORDER BY YEAR ASC
       , MONTH ASC;