WITH RECURSIVE GEN AS (
    -- 1세대
    SELECT 
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    -- 다음 세대
    SELECT
        E.ID,
        E.PARENT_ID,
        G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GEN G
        ON E.PARENT_ID = G.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM GEN
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION;
