-- 생산일자가 2022년 5월인 식품들의 총매출
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES FROM FOOD_PRODUCT P
JOIN FOOD_ORDER F ON P.PRODUCT_ID = F.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID
ORDER BY 3 DESC, 1;
