WITH hours AS (
    SELECT 0 AS hour FROM DUAL
    UNION ALL SELECT 1 FROM DUAL
    UNION ALL SELECT 2 FROM DUAL
    UNION ALL SELECT 3 FROM DUAL
    UNION ALL SELECT 4 FROM DUAL
    UNION ALL SELECT 5 FROM DUAL
    UNION ALL SELECT 6 FROM DUAL
    UNION ALL SELECT 7 FROM DUAL
    UNION ALL SELECT 8 FROM DUAL
    UNION ALL SELECT 9 FROM DUAL
    UNION ALL SELECT 10 FROM DUAL
    UNION ALL SELECT 11 FROM DUAL
    UNION ALL SELECT 12 FROM DUAL
    UNION ALL SELECT 13 FROM DUAL
    UNION ALL SELECT 14 FROM DUAL
    UNION ALL SELECT 15 FROM DUAL
    UNION ALL SELECT 16 FROM DUAL
    UNION ALL SELECT 17 FROM DUAL
    UNION ALL SELECT 18 FROM DUAL
    UNION ALL SELECT 19 FROM DUAL
    UNION ALL SELECT 20 FROM DUAL
    UNION ALL SELECT 21 FROM DUAL
    UNION ALL SELECT 22 FROM DUAL
    UNION ALL SELECT 23 FROM DUAL
 -- 0~23까지의 더미 테이블 생성
    )
SELECT    h.hour AS hour
        , COUNT(o.datetime) AS count
FROM      hours h
LEFT JOIN animal_outs o
          ON h.hour = TO_NUMBER(TO_CHAR(o.datetime, 'HH24'))
       -- 숫자형으로 변환해서 조인
GROUP BY  h.hour
ORDER BY  hour ASC;