SELECT
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM DEVELOPERS D
CROSS JOIN (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
) FE
WHERE (D.SKILL_CODE & FE.CODE) > 0
ORDER BY D.ID;
