-- 생일 3월 여성 조회 / 전화번호 null 이면 제외
SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') FROM MEMBER_PROFILE
WHERE TO_CHAR(DATE_OF_BIRTH, 'MM') = '03' AND GENDER = 'W'
AND TLNO IS NOT NULL
ORDER BY 1;