-- 완료된 중고 거래의 총금액이 70만원 이상인 사람
-- 총거래금액 기준 오름차순
SELECT U.USER_ID, U.NICKNAME, B.PRICE AS TOTAL_SALES FROM USED_GOODS_USER U
JOIN (SELECT WRITER_ID, SUM(PRICE) AS PRICE FROM USED_GOODS_BOARD
      WHERE STATUS = 'DONE'
      GROUP BY WRITER_ID
      HAVING SUM(PRICE) >= 700000) B ON B.WRITER_ID = U.USER_ID
      
ORDER BY 3;