SELECT U.USER_ID, U.NICKNAME, SUM(G.PRICE) AS TOTAL_SALES FROM USED_GOODS_USER U
JOIN USED_GOODS_BOARD G ON U.USER_ID = G.WRITER_ID
WHERE G.STATUS = "DONE"
GROUP BY G.WRITER_ID
HAVING SUM(G.PRICE) >= 700000
ORDER BY TOTAL_SALES;
