SELECT MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE, "%Y-%m-%d") REVIEW_DATE
FROM (
    SELECT MEMBER_ID, COUNT(REVIEW_ID)
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY 2 DESC LIMIT 1
) MR
JOIN REST_REVIEW RR ON MR.MEMBER_ID = RR.MEMBER_ID
JOIN MEMBER_PROFILE MP ON RR.MEMBER_ID = MP.MEMBER_ID
ORDER BY 3, 2;