SELECT c.MEMBER_NAME, e.REVIEW_TEXT, TO_CHAR(e.REVIEW_DATE, 'YYYY-MM-DD') as REVIEW_DATE
FROM MEMBER_PROFILE c
JOIN (SELECT a.MEMBER_ID, COUNT(b.REVIEW_ID) as cnt
FROM MEMBER_PROFILE a
JOIN REST_REVIEW b
ON a.MEMBER_ID = b.MEMBER_ID
GROUP BY a.MEMBER_ID
ORDER BY cnt desc
FETCH FIRST ROWS ONLY
) d
ON c.MEMBER_ID = d.MEMBER_ID
JOIN REST_REVIEW e
ON c.MEMBER_ID = e.MEMBER_ID
ORDER BY review_date, review_text