-- 희귀도가 RARE 인 아이템들의
-- 모든 다음 업그레이드 아이템의 정보

SELECT T.ITEM_ID, I.ITEM_NAME, I.RARITY FROM ITEM_TREE T
JOIN ITEM_INFO I ON T.ITEM_ID = I.ITEM_ID
WHERE PARENT_ITEM_ID IN(SELECT ITEM_ID FROM ITEM_INFO
                WHERE RARITY = 'RARE')
ORDER BY T.ITEM_ID DESC;