-- 부모의 형질을 모두 보유한 대장균의 정보
-- 형질 비교 > 2진수 > &

SELECT C.ID, C.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA C, ECOLI_DATA P
WHERE C.PARENT_ID = P.ID
AND (C.GENOTYPE & P.GENOTYPE) = P.GENOTYPE
ORDER BY C.ID;
