-- 보호시작일보다 입양일이 더 빠른 동물의 아이디와 이름
-- 보호 시작일이 빠른 순으로 > 오름차순
SELECT I.ANIMAL_ID, I.NAME FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME;