SELECT
    MONTH, CAR_ID , COUNT(*) AS RECORDS
FROM ( 
    SELECT
        CAR_ID,
        EXTRACT(MONTH FROM START_DATE) AS MONTH,
        COUNT(*) OVER (PARTITION BY CAR_ID) AS RENTAL_COUNT
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE >= DATE '2022-08-01' AND
        START_DATE <= DATE '2022-10-31'
    )
WHERE
    RENTAL_COUNT >= 5
GROUP BY
    MONTH, CAR_ID
ORDER BY
    MONTH ASC,
    CAR_ID DESC;