SELECT YEAR, (M - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA AS A 
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS M
     FROM ECOLI_DATA
     GROUP BY YEAR(DIFFERENTIATION_DATE)) AS T
ON YEAR(A.DIFFERENTIATION_DATE) = T.YEAR
ORDER BY YEAR, YEAR_DEV