-- 자동차 종류가 세단이고 10월에 대여를 시작한 기록이 있는 자동차
-- 중복이 없어야 함
SELECT C.CAR_ID FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '세단' AND TO_CHAR(H.START_DATE, 'YYYY-MM') >= '2022-10'
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC;