SELECT DISTINCT C.CAR_ID FROM CAR_RENTAL_COMPANY_CAR C
LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
ON C.CAR_ID = RH.CAR_ID
WHERE RH.START_DATE BETWEEN '2022-10-01' AND '2022-10-31' AND C.CAR_TYPE = '세단'
ORDER BY 1 DESC;