SELECT DISTINCT(CAR_ID) FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_ID IN (SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE TO_CHAR(START_DATE, 'YYYY-MM') = '2022-10')
AND CAR_TYPE = '세단'
ORDER BY 1 DESC;