SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE FROM USED_GOODS_BOARD b
INNER JOIN USED_GOODS_REPLY r ON b.board_id = r.board_id
WHERE b.CREATED_DATE LIKE "%2022-10%" ORDER BY r.CREATED_DATE, b.TITLE;