-- 10-05 등록된 게시글ID, 작성자ID, 게시글 제목, 가격, 거래상태
-- 거래상태: SALE, RESERVED, DONE
-- 게시글ID 내림차순
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE,
CASE STATUS WHEN 'SALE' THEN '판매중' 
            WHEN 'RESERVED' THEN '예약중'
            WHEN 'DONE' THEN '거래완료'
            END AS STATUS
FROM USED_GOODS_BOARD
WHERE TO_CHAR(CREATED_DATE, 'YYYY-MM-DD') = '2022-10-05'
ORDER BY 1 DESC;