SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES FROM BOOK B
JOIN BOOK_SALES S ON S.BOOK_ID = B.BOOK_ID
WHERE S.SALES_DATE BETWEEN TO_DATE('20220101', 'YYYY-MM-DD') AND TO_DATE('20220131', 'YYYY-MM-DD')
GROUP BY CATEGORY
ORDER BY CATEGORY;