SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE)
IN (SELECT CATEGORY, MAX(PRICE) FROM FOOD_PRODUCT
   WHERE CATEGORY IN ('과자', '김치', '국', '식용유')
   GROUP BY CATEGORY)
ORDER BY 2 DESC;